### ISSUE TITLE
Doesn't work on Php 8.0

### ISSUE THREAD

**Issue by Tlem33** [rubo77/AutoIndex#2]
This script doesn't work on Php 8.x.
Do you plan to update it?

**Comment by rubo77** [comment]
Yes.
If I find the time.

Shouldn't be much to change.


PRs are welcome

**Comment by rubo77** [comment]
Check

https://github.com/Dark1-dev/AutoIndex-Php8

**Comment by Tlem33** [comment]
Hi rubo77.
The modified version from Dark1 seems to work like a charm on PhP 8.1 and PhP 8.2.  ^^

Thank you so much. If I can buy you a bear, I will do it with pleasure.

**Comment by rubo77** [comment]
fixed with 014b99286529c245ecf833b563601f91a112813c
